name: warcrafty
description: A library used to read / write dbc / db2 file, and will support mpq generate in the future.
version: 0.0.1
homepage: https://warcrafty.foxwow.xyz

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
